---
abstract: 'Load BarnOwl filters from ~/.owl/classfilters'
author:
  - 'Kevin Riggle, C<< <kevinr at free-dissociation.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: BarnOwl-Module-ClassFilters
no_index:
  directory:
    - inc
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.01
